### PR TITLE
Revert "style: pass by `const` reference" : Changes Breaking code

### PR DESCRIPTION
**Pull request by ujjwall-R**
Reverts ujjwall-R/Dree#74

### CODE REVIEW

**Comment by vil02** [comment]
@ujjwall-R: I am puzzled. Could you please explain how #74 broke the code?

**Comment by ujjwall-R** [comment]
can you test with the changes you made.
Please look into it once. Once fixed we can go with another PR. No issues with that. By mistake I merged thinking it as a minor change but now noticed this error. Please resolve this.
image

**Comment by vil02** [comment]
I do not understand. On _my end_ it looks like that:
image

Here are the steps, which I took (assuming that my working directory this repository): 
- run `mkdir compile`,
- run `make`,
- add a line `alias dree='<some_path>/Dree/dree.sh'` to `~/.bashrc`,
- run `source ~/.bashrc`,
- run `dree 3` (or simply run `<some_path>/Dree/dree.sh 3`).

Could you please tell me where am I making a mistake? It looks to me like some problem with the Makefile.

**Comment by ujjwall-R** [comment]
Lets find and fix this. I will also look into it. Its strange that it is working in your setup.

**Comment by vil02** [comment]
Did you repeat the steps, which I described on a _clean_ setup?

**Comment by ujjwall-R** [comment]
yep. I found the issue.
in the Args() constructor, we are passing char* in string&.

Make sure to change all the places the constructor is called to ensure type check.

**Comment by vil02** [comment]
I think I understand the problem: some of the header files changed in #74, but `make` is not aware of that.

Try to add these flags `-MMD -MP` into:
https://github.com/ujjwall-R/Dree/blob/1993898bc9feba0dfc5d2240f0141e054e8d192a/Makefile#L4

**Comment by vil02** [comment]
> yep. I found the issue. in the Args() constructor, we are passing char* in string&.
> 
> Make sure to change all the places the constructor is called to ensure type check.
> 
> Can you fix this?

This is not a problem: `char*` can be implicitly casted into `std::string` (i.e. `std::string` has a constructor expecting `const char*`).

**Comment by ujjwall-R** [comment]
> > yep. I found the issue. in the Args() constructor, we are passing char* in string&.
> > Make sure to change all the places the constructor is called to ensure type check.
> > Can you fix this?
> 
> This is not a problem: `char*` can be implicitly casted into `std::string` (i.e. `std::string` has a constructor expecting `const char*`).

yeah...but this is causing the problem in my machine.

**Comment by ujjwall-R** [comment]
Implicit conversions should be prevented; https://www.geeksforgeeks.org/how-to-prevent-implicit-conversions-in-cpp/

**Comment by vil02** [comment]
The implicit conversion has nothing to do with that problem (the current version also does it).

**Comment by ujjwall-R** [comment]
> The implicit conversion has nothing to do with that problem (the current version also does it).

But here explicitly converting and passing the value to Args() solve this issue. We should make this as an issue to convert all implicit conversions to explicit.

**Comment by vil02** [comment]
Look, this is what happened:
- you merged #74 and pulled my changes (note: `Args.h` changed),
- you run something `dree 3`, which runs `make run`. `make` detected that the object files are out of date., but `main.o` was fine (but, this is not true, since `main.cpp` is including `Args.h`, so `main.o` should be regenrated),
- the not-updated `main.o` was trying to use the function `Args(long long dep, string path)`, which did not exit anymore.

**Comment by ujjwall-R** [comment]
Lets fix this. Will you take this issue?

**Comment by vil02** [comment]
I will create a PR adding the mentioned flags.

**Comment by VivekRastogi799** [comment]
Nice Job

**Pull request merged**
