### PR TITLE
Publish to AUR 

### PR DESCRIPTION
**Pull request by BAGUVIX456**
Added PKGBUILD and .SRCINFO

### CODE REVIEW

**Comment by ujjwall-R** [comment]
Resolve the conflicts please.

**Comment by BAGUVIX456** [comment]
My bad, fixed it now

**Comment by ujjwall-R** [comment]
> My bad, fixed it now

Why is endl added in main.cpp

**Comment by BAGUVIX456** [comment]
I just modified the output. I'll revert all changes done to main.cpp if you want to

**Comment by ujjwall-R** [comment]
> I just modified the output. I'll revert all changes done to main.cpp if you want to

Any specific reason to modify the output?

**Comment by BAGUVIX456** [comment]
No, there's no specific reason other than aesthetics. Nothing directly related to the issue

**Comment by ujjwall-R** [comment]
> No, there's no specific reason other than aesthetics. Nothing directly related to the issue

then lets not change it.

**Review by ujjwall-R — APPROVED** [review]

**Pull request merged**
