### PR TITLE
Added a help flag

### LINKED ISSUE #41: Missing feature: Add --help flag to the command
It would be great to have a `--help` flag passed with the `dree` command for better understanding of currently available command options supported. 

**Why is this useful?**
Helpful for the first time users.

### PR DESCRIPTION
**Pull request by Abdelra6**
fixes #41

### CODE REVIEW

**Comment by ujjwall-R** [comment]
Please make PR to dev branch

**Comment by Abdelra6** [comment]
Done

**Comment by Abdelra6** [comment]
Is it good now or should I resolve these conflicts? @ujjwall-R

**Comment by ujjwall-R** [comment]
> Is it good now or should I resolve these conflicts? @ujjwall-R

resolve the conflicts. There are more conflicts.

**Comment by Abdelra6** [comment]
> > Is it good now or should I resolve these conflicts? @ujjwall-R
> 
> resolve the conflicts. There are more conflicts.

How to solve them? my branch is up-to-date with the upstream

**Review by ujjwall-R — APPROVED** [review]

**Pull request merged**
